"""Background report generation.

Stub implementation: walks through a fixed set of stages with delays so the
frontend has realistic progress to render. Replace `_compose_report_body`
with a real model call when wired up to an LLM.
"""
from __future__ import annotations

import threading
import time

from . import storage

_STAGES = [
    ("Gathering filings", 12),
    ("Reviewing recent news", 28),
    ("Analyzing financials", 48),
    ("Synthesizing insights", 72),
    ("Drafting report", 90),
    ("Finalizing", 100),
]


def _compose_report_body(
    company_name: str, report_type: str, audience: str, language: str
) -> str:
    if language == "zh":
        return (
            f"# {report_type} — {company_name}\n\n"
            f"_受众:{audience}_\n\n"
            "## 摘要\n\n"
            f"这是关于 {company_name} 的占位{report_type}报告。"
            "将 `server/generator.py` 接入真实模型以生成实际内容。\n\n"
            "## 要点\n\n"
            f"- 报告类型:{report_type}\n"
            f"- 受众:{audience}\n"
            "- 由 BSH Research Center 占位生成器输出。\n"
        )
    return (
        f"# {report_type} — {company_name}\n\n"
        f"_Prepared for: {audience}_\n\n"
        "## Summary\n\n"
        f"This is a placeholder {report_type.lower()} for {company_name}. "
        "Wire `server/generator.py` to a real model to populate this section "
        "with actual findings.\n\n"
        "## Key Points\n\n"
        f"- Report type: {report_type}\n"
        f"- Audience: {audience}\n"
        "- Generated by the BSH Research Center scaffolding generator.\n"
    )


def _run(report_id: str) -> None:
    report = storage.get_report(report_id)
    if report is None:
        return
    storage.update_report(report_id, status="running", stage="Starting", progress=1)

    for label, pct in _STAGES:
        time.sleep(1.2)
        storage.append_report_stage(report_id, {"label": label, "progress": pct})
        storage.update_report(report_id, stage=label, progress=pct)

    body = _compose_report_body(
        company_name=str(report.get("company_name") or report.get("company_id")),
        report_type=str(report.get("report_type")),
        audience=str(report.get("audience")),
        language=str(report.get("language") or "en"),
    )
    storage.update_report(
        report_id,
        status="complete",
        stage="Complete",
        progress=100,
        content=body,
    )


def start_generation(report_id: str) -> None:
    t = threading.Thread(target=_run, args=(report_id,), daemon=True)
    t.start()
